### PR TITLE
Feature/#72 fix rpcexception resolution

### LINKED ISSUE #72: Fix RPCException resolution
Since we switched from RSB to MQTT the RPCException resolution does not work anymore.
* Implement Test
* Fix resolution or find any other way to transmit the exception.

### PR DESCRIPTION
**Pull request by pLeminoq**
### :scroll: Description

Changes proposed in this pull request:
* Fix RPC Exception Resolution
* Write according unit tests

### CODE REVIEW

File: module/communication/mqtt/src/main/java/org/openbase/jul/communication/mqtt/RPCServerImpl.kt [hunk 1]
```diff
@@ -142,8 +142,8 @@ class RPCServerImpl(scope: Scope, config: CommunicatorConfig) : RPCCommunicatorI
             responseBuilder.result = result
         } catch (ex: Exception) {
             when (ex) {
-                is InvocationTargetException, is CouldNotPerformException -> responseBuilder.error =
-                    ex.stackTraceToString()
+                is InvocationTargetException -> responseBuilder.error =
+                    ex.cause!!.stackTraceToString()
```
Comment (DivineThreepwood) [inline module/communication/mqtt/src/main/java/org/openbase/jul/communication/mqtt/RPCServerImpl.kt]: Try to avoid usage of `!!` in kotlin since the cause can be null, right? Thus, it would lead to a `Nullpointer` again. Just use something like `ex?.cause?.stackTraceToString()?:"UNKNOWN_ERROR"` or just `ex?.cause?.stackTraceToString()` in case `ressponseBuilder.errer` is nullable.

File: module/communication/mqtt/src/test/java/org/openbase/jul/communication/mqtt/IntegrationTest.kt [hunk 2]
```diff
@@ -19,6 +24,39 @@ class IntegrationTest : AbstractIntegrationTest() {
...
+        try {
+            rpcClient.callMethod(instance::couldNotPerform.name, Unit::class).get(1, TimeUnit.SECONDS)
+        } catch (ex: ExecutionException) {
+            ex.cause shouldNotBe null
+            ex.cause!!::class.java shouldBe RPCResolvedException::class.java
+            val rpcException = ex.cause!! as RPCResolvedException
+
+            rpcException.cause shouldNotBe null
+            rpcException.cause!!::class.java shouldBe CouldNotPerformException::class.java
+            val initialCause: CouldNotPerformException = rpcException.cause!! as CouldNotPerformException
```
Comment (DivineThreepwood) [inline module/communication/mqtt/src/test/java/org/openbase/jul/communication/mqtt/IntegrationTest.kt]: Again, I would recommend to replace all `!!` by `?.`

File: module/communication/mqtt/src/test/java/org/openbase/jul/communication/mqtt/RPCClientImplTest.kt [hunk 3]
```diff
@@ -172,13 +174,16 @@ internal class RPCClientImplTest {
...
 
             callback.accept(mqtt5Publish)
 
             val exception = shouldThrow<ExecutionException> { rpcFuture.get() }
-            exception.cause!!::class.java shouldBe RPCException::class.java
-            exception.cause!!.message shouldBe response.error
+            exception.cause!!::class.java shouldBe RPCResolvedException::class.java
+            val resolvedException = exception.cause!!
+            resolvedException.cause!!::class.java shouldBe CouldNotPerformException::class.java
+            resolvedException.cause!!.message shouldBe errorMessage
```
Comment (DivineThreepwood) [inline module/communication/mqtt/src/test/java/org/openbase/jul/communication/mqtt/RPCClientImplTest.kt]: Same here, `!!` -> `?.`

File: module/communication/default/src/test/java/org/openbase/jul/communication/exception/RPCResolvedExceptionTest.java [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+     * @param ex the exception from which the stack trace is printed
+     * @return the stack trace as a string
+     */
+    private String stackTraceToString(final Exception ex) {
+        final StringWriter stringWriter = new StringWriter();
+        final PrintWriter printWriter = new PrintWriter(stringWriter);
+        ex.printStackTrace(printWriter);
+        return stringWriter.toString();
+    }
+}
```
Comment (DivineThreepwood) [inline module/communication/default/src/test/java/org/openbase/jul/communication/exception/RPCResolvedExceptionTest.java]: Is there any special reason why you introduced this method again instead of writing the `Test` in kotlin were the method would be available anyway? Is your intention here to test the plain `java` api usage?

**Review by DivineThreepwood — CHANGES_REQUESTED** [review]

**Comment by DivineThreepwood** [comment]
Thanks for the PR :)

File: module/communication/mqtt/src/main/java/org/openbase/jul/communication/mqtt/RPCServerImpl.kt (hunk 1 above)
Comment (pLeminoq) [reply module/communication/mqtt/src/main/java/org/openbase/jul/communication/mqtt/RPCServerImpl.kt]: :+1:

File: module/communication/mqtt/src/test/java/org/openbase/jul/communication/mqtt/IntegrationTest.kt (hunk 2 above)
Comment (pLeminoq) [reply module/communication/mqtt/src/test/java/org/openbase/jul/communication/mqtt/IntegrationTest.kt]: :+1:

File: module/communication/mqtt/src/test/java/org/openbase/jul/communication/mqtt/RPCClientImplTest.kt (hunk 3 above)
Comment (pLeminoq) [reply module/communication/mqtt/src/test/java/org/openbase/jul/communication/mqtt/RPCClientImplTest.kt]: :+1:

File: module/communication/default/src/test/java/org/openbase/jul/communication/exception/RPCResolvedExceptionTest.java (hunk 4 above)
Comment (pLeminoq) [reply module/communication/default/src/test/java/org/openbase/jul/communication/exception/RPCResolvedExceptionTest.java]: :+1:

**Review by DivineThreepwood — APPROVED** [review]
