### PR TITLE
117 fix test container setup

### LINKED ISSUE #117: Fix test container setup.
Test containers does not support the latest docker version and has to be updated.
MQTT Container should be reused and not restarted before each test out of performance reasons.

### PR DESCRIPTION
**Pull request by DivineThreepwood**
### :scroll: Description

Changes proposed in this pull request:
* Make sure mqtt test container is reused for all tests.
* Upgrade test container dependency because it was no longer compatible with the latest docker version.

### CODE REVIEW

File: module/communication/mqtt/src/main/java/org/openbase/jul/communication/mqtt/SharedMqttClient.kt [hunk 1]
```diff
@@ -14,6 +14,7 @@ import com.hivemq.client.mqtt.mqtt5.message.unsubscribe.Mqtt5Unsubscribe
 import com.hivemq.client.mqtt.mqtt5.message.unsubscribe.Mqtt5UnsubscribeBuilder
 import com.hivemq.client.mqtt.mqtt5.message.unsubscribe.unsuback.Mqtt5UnsubAck
 import org.openbase.jul.communication.config.CommunicatorConfig
+import org.openbase.jul.exception.tryOrNull
```
Comment (lhuxohl) [inline module/communication/mqtt/src/main/java/org/openbase/jul/communication/mqtt/SharedMqttClient.kt]: imported but I don't see it used anywhere

File: module/communication/mqtt/src/test/java/org/openbase/jul/communication/mqtt/IntegrationTest.kt [hunk 2]
```diff
@@ -22,7 +22,7 @@ import kotlin.concurrent.withLock
 class IntegrationTest : AbstractIntegrationTest() {
 
     private val scope = ScopeProcessor.generateScope("/test/integration")
-    private val config = CommunicatorConfig(brokerHost, brokerPort)
+    private val config get() = CommunicatorConfig(brokerHost!!, brokerPort!!)
```
Comment (lhuxohl) [inline module/communication/mqtt/src/test/java/org/openbase/jul/communication/mqtt/IntegrationTest.kt]: Please add proper null handling

File: module/communication/mqtt/src/test/java/org/openbase/jul/communication/mqtt/SharedMqttClientTest.kt [hunk 3]
```diff
@@ -12,10 +12,12 @@ import org.openbase.jul.communication.config.CommunicatorConfig
 
 internal class SharedMqttClientTest : AbstractIntegrationTest() {
 
+    private val config get() = CommunicatorConfig(brokerHost!!, brokerPort!!)
```
Comment (lhuxohl) [inline module/communication/mqtt/src/test/java/org/openbase/jul/communication/mqtt/SharedMqttClientTest.kt]: see above

File: module/communication/mqtttest/src/main/kotlin/org/openbase/jul/communication/mqtt/test/MqttBrokerManager.kt [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+                        "listener $port"
+                    )
+                )
+                MqttBrokerContainer()
+                    .withExposedPorts(port)
+                    .withCopyFileToContainer(
+                        MountableFile.forHostPath(mosquittoConfig.toString()),
+                        "/mosquitto/config/mosquitto.conf"
+                    )
+                    .apply { withStartupTimeout(Duration.ofSeconds(30)).start() }
```
Comment (lhuxohl) [inline module/communication/mqtttest/src/main/kotlin/org/openbase/jul/communication/mqtt/test/MqttBrokerManager.kt]: Magic number. Please export to const

File: versions.properties [hunk 5]
```diff
@@ -6,66 +6,480 @@
...
+##        # available=6.0.0-M1
+##        # available=6.0.0-M2
+##        # available=6.0.0-RC1
+##        # available=6.0.0-RC2
+##        # available=6.0.0-RC3
+##        # available=6.0.0
+##        # available=6.0.1
+##        # available=6.0.2
+##        # available=6.0.3
+##        # available=6.1.0-M1
```
Comment (lhuxohl) [inline versions.properties:54]: What is the purpose of this?

**Review by lhuxohl — CHANGES_REQUESTED** [review]

File: versions.properties (hunk 5 above)
Comment (DivineThreepwood) [reply versions.properties:54]: this file is managed by gradle (checkout readme). Its just listing all available updates.

File: module/communication/mqtttest/src/main/kotlin/org/openbase/jul/communication/mqtt/test/MqttBrokerManager.kt (hunk 4 above)
Comment (DivineThreepwood) [reply module/communication/mqtttest/src/main/kotlin/org/openbase/jul/communication/mqtt/test/MqttBrokerManager.kt]: I introduced a const, however, I am not sure if this really improved the readability of the code.

**Review by lhuxohl — APPROVED** [review]

**Review by lhuxohl — APPROVED** [review]
